sonar.host.url=https://sonarcloud.io
sonar.projectKey=fit-ai
sonar.projectName=FiT-AI
sonar.organization=nuafah

sonar.sources=backend/shared,backend/squat,backend/plank,backend/lunges,backend/wall_sit
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.python.coverage.reportPaths=backend/coverage.xml

# Exclusions
sonar.exclusions=\
  venv/**,\
  __pycache__/**,\
  dataset/**,\
  **/models/**,\
  recordings_squat/**,\
  **/*.pyc,\
  **/squat_streaming_old.py,\
  tests/**,\
  scripts/**

# Coverage exclusions
sonar.coverage.exclusions=\
  **/*_streaming.py,\
  **/train_*.py,\
  backend/shared/training_utils.py

sonar.test.inclusions=backend/tests/**/*.py
