sonar.projectKey=fit-ai
sonar.projectName=FiT-AI
sonar.organization=nuafah

sonar.sources=backend/shared,backend/squat,backend/plank,backend/lunges,backend/wall_sit
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.exclusions=**/train_*.py,**/__pycache__/**,**/models/**,**/dataset/**
sonar.test.inclusions=backend/tests/**/*.py
