sonar.host.url=https://sonarcloud.io
sonar.projectKey=Pichayanon_FiT-AI
sonar.projectName=FiT-AI
sonar.organization=pichayanon
sonar.projectVersion=1.0.1

sonar.sources=shared,squat,plank,lunges,wall_sit
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=\
  venv/**,\
  __pycache__/**,\
  dataset/**,\
  **/models/**,\
  recordings_squat/**,\
  **/*.pyc,\
  **/squat_streaming_old.py,\
  **/train_*.py,\
  scripts/**

# Coverage exclusions
sonar.coverage.exclusions=\
  **/*_streaming.py,\
  **/train_*.py,\
  lunges/session.py,\
  squat/session.py,\
  shared/side_window_session.py

sonar.test.inclusions=tests/**/*.py
sonar.test.exclusions=tests/api/test_api.py
